name: igshark
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  # adapty_flutter: ^1.0.14
  bloc: ^8.1.0
  cached_network_image: ^3.2.2
  cloud_firestore: ^3.4.6
  cloud_functions: ^3.3.7
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_image_stack: ^0.0.6
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  go_router: ^4.1.1
  google_fonts: ^3.0.1
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  http: ^0.13.4
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  mrx_charts: ^0.1.3
  purchases_flutter: ^4.4.0
  rxdart: ^0.27.5
  shimmer: ^2.0.0
  story_view: ^0.13.2
  timeago: ^3.3.0
  url_launcher: ^6.1.6
  webview_cookie_manager: ^2.0.6
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  mockito: ^5.2.0
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with as
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
          style: normal
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
